### ISSUE TITLE
Gem::RemoteFetcher::FetchError with bad response forbidden 403 when gem installation

### ISSUE THREAD

**Issue by topdice-dev** [rubygems/rubygems.org#2990]
C:\Users\helle>ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [i386-mingw32]

C:\Users\helle>gem source --add https://api.rubygems.org/
https://api.rubygems.org/ added to sources

C:\Users\helle>call gem install roo
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.3-x64-unknown.gemspec.rz)

C:\Users\helle>call gem install rails
Fetching: activesupport-7.0.2.3.gem (100%)
ERROR:  Error installing rails:
        There are no versions of activesupport (= 7.0.2.3) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
        activesupport requires Ruby version >= 2.7.0. The current ruby version is 2.5.0.

C:\Users\helle>call gem install sanitize
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://api.rubygems.org/quick/Marshal.4.8/nokogiri-1.13.3-x64-unknown.gemspec.rz)

**Comment by topdice-dev** [comment]
No paricular reason to gem source add.
I didn't knew public gem server URL. and source https://rubygems.org already present in the cache but installation doen't worked.

**Comment by simi** [comment]
Can you check what in your sources right now? You can use `gem source` command. Also public gem server should be part of gem sources by default and there should be no need  What's the current problem? Still the same?

**Comment by deivid-rodriguez** [comment]
Also, since the `gem install rails` command wasn't about to figure out that Rails 7 is not compatible with your Ruby version, that suggests you're using a very old RubyGems. Can you upgrade RubyGems with `gem update --system`?

**Comment by topdice-dev** [comment]
C:\Ruby25\bin>gem source
*** CURRENT SOURCES ***

https://rubygems.org/
https://api.rubygems.org/

and
C:\Ruby25\bin>gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.3.9.gem (100%)
Successfully installed rubygems-update-3.3.9
Parsing documentation for rubygems-update-3.3.9
Installing ri documentation for rubygems-update-3.3.9
Installing darkfish documentation for rubygems-update-3.3.9
Done installing documentation for rubygems-update after 233 seconds
Parsing documentation for rubygems-update-3.3.9
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.3.9
  Successfully built RubyGem
  Name: bundler
  Version: 2.3.9
  File: bundler-2.3.9.gem
Bundler 2.3.9 installed
RubyGems 3.3.9 installed
Regenerating binstubs
Regenerating plugins
Parsing documentation for rubygems-3.3.9
Installing ri documentation for rubygems-3.3.9

**Comment by topdice-dev** [comment]
after gem update --system, it works well. thanks.

**Comment by simi** [comment]
Glad you have fixed your problem. I suggest to run `gem source --remove https://api.rubygems.org/` and ensure by running gem source` it is gone. It seems it is still present.

**Comment by topdice-dev** [comment]
Sure. Thanks for your kindness.

C:\Ruby25\bin>gem source --remove https://api.rubygems.org/
https://api.rubygems.org/ removed from sources

C:\Ruby25\bin>gem source
*** CURRENT SOURCES ***

https://rubygems.org/
